package ru.lets.counting.domain.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import ru.lets.counting.domain.Category;
import ru.lets.counting.domain.Purchase;

/**
 * Class _Categories was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Categories extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String TITLE_PROPERTY = "title";
    public static final String CATEGORIES_ARRAY_PROPERTY = "categoriesArray";
    public static final String PURCHASES_ARRAY_PROPERTY = "purchasesArray";
    public static final String TO_CATEGORIES_PROPERTY = "toCategories";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void addToCategoriesArray(Category obj) {
        addToManyTarget(CATEGORIES_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromCategoriesArray(Category obj) {
        removeToManyTarget(CATEGORIES_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Category> getCategoriesArray() {
        return (List<Category>)readProperty(CATEGORIES_ARRAY_PROPERTY);
    }


    public void addToPurchasesArray(Purchase obj) {
        addToManyTarget(PURCHASES_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPurchasesArray(Purchase obj) {
        removeToManyTarget(PURCHASES_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Purchase> getPurchasesArray() {
        return (List<Purchase>)readProperty(PURCHASES_ARRAY_PROPERTY);
    }


    public void setToCategories(Category toCategories) {
        setToOneTarget(TO_CATEGORIES_PROPERTY, toCategories, true);
    }

    public Category getToCategories() {
        return (Category)readProperty(TO_CATEGORIES_PROPERTY);
    }


}
