package ru.lets.counting.domain.auto;

import org.apache.cayenne.CayenneDataObject;

import ru.lets.counting.domain.Category;

/**
 * Class _Purchase was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Purchase extends CayenneDataObject {

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String TO_CATEGORIES_PROPERTY = "toCategories";

    public static final String ID_PK_COLUMN = "id";

    public void setAmount(Integer amount) {
        writeProperty(AMOUNT_PROPERTY, amount);
    }
    public Integer getAmount() {
        return (Integer)readProperty(AMOUNT_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setToCategories(Category toCategories) {
        setToOneTarget(TO_CATEGORIES_PROPERTY, toCategories, true);
    }

    public Category getToCategories() {
        return (Category)readProperty(TO_CATEGORIES_PROPERTY);
    }


}
